export const keyToNote = {
  A: 'D6',
  S: 'B5',
  D: 'G5',
  F: 'E5',
  G: 'C5',
  H: 'A4',
  J: 'F4',
  K: 'D4',
  L: 'C4',
  Q: 'E4',
  W: 'G4',
  E: 'B4',
  R: 'D5',
  T: 'F5',
  Y: 'A5',
  U: 'C6',
  I: 'E6',
};

export const kalimbaEvents = {
  NOTE_PLAY: 'note:play',
  KEY_EDIT: 'key:edit',
  KEY_UPDATE: 'key:update',
  SEQUENCE_MODE: 'sequence:mode',
  SEQUENCE_START: 'sequence:start',
  SEQUENCE_END: 'sequence:end',
};

export const colorMap = {
    A: '#F94144',
    B: '#F3722C',
    C: '#F8961E',
    D: '#F9844A',
    E: '#F9C74F',
    F: '#90BE6D',
    G: '#43AA8B',
    H: '#4D908E',
    I: '#577590',
    J: '#277DA1',
    K: '#577590',
    L: '#6D597A',
    M: '#B56576',
    N: '#E56B6F',
    O: '#EAAC8B',
    P: '#FFD6A5',
    Q: '#FDFFB6',
    R: '#CAFFBF',
    S: '#9BF6FF',
    T: '#A0C4FF',
    U: '#BDB2FF',
    V: '#FFC6FF',
    W: '#FFADAD',
    X: '#FFD6A5',
    Y: '#FDFFB6',
    Z: '#CAFFBF',
  };